### PR TITLE
Update CqlTemplate.java: add missing 'throws'

### PR DESCRIPTION
**Pull request by rs017991**
While these process methods have quite a few problems and inconsistencies with respect to the exception handling, only the more egregious 'throw' omissions are addressed in this pull request.

### CODE REVIEW

**Comment by prowave** [comment]
Thanks for the contribution.  Please add unit and integration tests so we can verify there is no negative impact from this change.

**Comment by prowave** [comment]
After reviewing this closer, no need for test cases..these are clearly bugs.

As for the Exception handling, DataStax has changed their exception hierarchy mulitple times on us.  Please feel free to update the ExceptionTranslator if needed.  That change will require tests.

Thanks.

**Comment by rs017991** [comment]
If I'm able to find some time to deep dive into the Exception Handling (unlikely at the present), I'll create a separate PR for those changes; in the meantime, you may feel free to merge this little guy at your pleasure.

Thanks

**Comment by mp911de** [comment]
Can you please sign, if you haven't done already, the [CLA form](https://support.springsource.com/spring_committer_signup) for `Spring Data Access` with project lead `Oliver Gierke` and add your CLA Number as comment to this issue or [DATACASS-262](https://jira.spring.io/browse/DATACASS-262).

**Comment by mp911de** [comment]
That's merged with 21686dd448395479899ae369c77146a7ed8493de.

**Pull request closed without merging**
