### PR TITLE
DATACASS-172 - Support for UDTs.

### PR DESCRIPTION
**Pull request by mp911de**
We now support Cassandra User-defined types. UDTs can be created using CQL generators and used inside of mapped domain classes. User-defined types can be used either raw as `UDTValue` that is passed through or as mapped object. Mapped UDTs must be annotated with `@UserDefinedType`. Types are included into schema generation so known and defined UDTs are created before any tables are created. UDTs can be used with set and list collection types and in primary keys. UDTs can also be used in repository query methods as query predicates.
Updating UDTs will update the whole UDT.

```
@UserDefinedType
public class Address {
  String city;
  String country;
}

@Table
public class Person {

  @Id String id;
  Address address;
  UDTValue genericUdt;
}
```

---

Related ticket: [DATACASS-172](https://jira.spring.io/browse/DATACASS-172)
Depends on: #83

### CODE REVIEW

**Comment by mp911de** [comment]
Reminder: Is there a better approach than registering an `UserTypeResolver` in the `MappingContext`? That requires users of Spring Boot and XML-Namespace support to take additional action.

**Comment by Shoaib627** [comment]
Hi can some one please let me know when this feature will be merged to release branch?
If its going to take some time how can I use the build with this feature.

**Comment by mp911de** [comment]
@Shoaib627 Here's a link to the [Ingalls Release Train](https://github.com/spring-projects/spring-data-commons/wiki/Release-Train-Ingalls) containing all dates. It would be amazing getting feedback on that feature. The currently only way how to get this dependency is checking out my repo and the branch and building the project (`mvn clean install`). You can then add following dependencies to your project:

```xml
<dependency>
    <groupId>org.springframework.data</groupId>
    <artifactId>spring-cql</artifactId>
    <version>1.5.0.DATACASS-172-SNAPSHOT</version>
</dependency>

<dependency>
    <groupId>org.springframework.data</groupId>
    <artifactId>spring-data-cassandra</artifactId>
    <version>1.5.0.DATACASS-172-SNAPSHOT</version>
</dependency>
```

**Comment by mp911de** [comment]
@olivergierke maybe you want to take a look on this one?

**Comment by jxblum** [comment]
Merged to `master` in revisions [1865c31](https://github.com/spring-projects/spring-data-cassandra/commit/1865c31708a4d99d0e00cc79ce92af24dd483604), [a36e7be](https://github.com/spring-projects/spring-data-cassandra/commit/a36e7beecb979720e790ce07ff7398c792b696ea), [2195374](https://github.com/spring-projects/spring-data-cassandra/commit/2195374c681d2d9d521cc6e3dc53a8cf9e8f46b6) and [c3584e6](https://github.com/spring-projects/spring-data-cassandra/commit/c3584e688305c094cab0dfd52292d21fb9793cae) for the _Spring Data Cassandra_ *1.5 RC1 (Ingalls)* release.

**Comment by jxblum** [comment]
Committed to `2.0.x` in revisions [ac868d2](https://github.com/spring-projects/spring-data-cassandra/commit/ac868d2f0a415962490b8e0582e1a086d30c55fa), [84f680e](https://github.com/spring-projects/spring-data-cassandra/commit/84f680ee3e9d8844fa0776278e1d0541770a4570), [cfa8a61](https://github.com/spring-projects/spring-data-cassandra/commit/cfa8a6177fae1bdd0cff8129aba47eb8451ac067) and [dcc34a2](https://github.com/spring-projects/spring-data-cassandra/commit/dcc34a284a6cb920639b38d1fc538742d4d413be) for the _Spring Data Cassandra_ **2.0 M1 (Kay)** release.

**Comment by warwing** [comment]
Hey,

I'm quite new to spring data in general, so may be my question is quite obvious, but...

I'am trying to understand how to use the UDTs - but I couldn't figure out how to "register" a UDT - so that it can be resolved by the mapping context.

I've seen this test:
https://github.com/spring-projects/spring-data-cassandra/blob/master/spring-data-cassandra/src/test/java/org/springframework/data/cassandra/mapping/CreateTableSpecificationBasicCassandraMappingContextUnitTests.java

There are two variants:
1) The approach with @CassandraType(type = Name.UDT, userTypeName = "human_udt")  ...
2) UserTypeResolver - but who can I get an instance of the UserType class? - In the test it's mocked...

I implemented the UDT as a class with @UserDefinedType annotation - and thought it should be usable without the @CassandraType annotation...
...for @Table there is a Repository that seems to be responsible for registering the type.
Is there a corresponding concept for UDTs?

When I execute my test, the following error occurs:
org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.data.cassandra.mapping.CassandraMappingContext]: Factory method 'cassandraMapping' threw exception; nested exception is java.lang.IllegalArgumentException: UserTypeResolver must not be null

Best regards,

Alex

**Comment by mp911de** [comment]
@warwing care to post your question on StackOverflow? That's not a general discussion forum.

**Pull request closed without merging**
