### PR TITLE
DATACASS-401 Making cqlTemplate and cassandraTemplate bean names consistent (it wa…

### PR DESCRIPTION
**Pull request by mateuszy**
…s confusing and wrong before; tests were failing because of non-existing bean of certain name).

- [x] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [x] There is a ticket in the bug tracker for the project in our [JIRA](https://jira.spring.io/browse/DATACASS).
- [x] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [x] You submit test cases (unit or integration tests) that back your changes.
- [ ] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@mateuszy Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-cassandra&pullRequestId=96)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-data-cassandra&pullRequestId=96) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@mateuszy Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-cassandra&pullRequestId=96)!

**Comment by mp911de** [comment]
Thanks for your PR. We have an earlier ticket [DATACASS-129](https://jira.spring.io/browse/DATACASS-129) that deals with this issue. That's a breaking change so the fix has to happen in Spring Data Casandra 2.0. Do you want to give the `TODO` you removed also a try?

`CassandraTemplateParser` should no longer extend `CassandraCqlTemplateParser` but simply `AbstractSingleBeanDefinitionParser` and the property reference to `session` needs to be added to `CassandraTemplateParser` too.

If not, then please don't remove the `TODO`.

**Comment by mateuszy** [comment]
@mp911de, I'll give a shot at this TODO as you suggested - thought I was enough to just prevent the misleading bean naming for now.

**Comment by mp911de** [comment]
That's merged and polished now.

**Pull request closed without merging**
