### PR TITLE
DATACASS-202 Misspelled ConsistencyLevel enum constants and DATACASS-217 Add support for LZ4 compression

### PR DESCRIPTION
**Pull request by myeh**
-  Fix for DATACASS-202
   - Fixed incorrect spelling for quorum
- Fix for DATACASS-217
   - Add support for LZ4 compression

### CODE REVIEW

**Comment by clem0110** [comment]
Hello.  Is there an ETA on when this change will be merged and released? We're running into this issue now and would love this fix.

**Comment by KarthicRaj** [comment]
Hi Admins, Can some one merge this PR. This is a very fundamental issue that needs to be part of the release at the earliest. Is there a frequency or schedule when the PRs are reviewed and merged.

**Comment by jeffnelson** [comment]
My team is also waiting on this fix getting into release.

**Comment by prowave** [comment]
I manually merged this PR since the branch was out of date.  This will be available in the 1.4.0.BUILD-SNAPSHOT tomorrow.

**Comment by prowave** [comment]
Merge reverted for administrative reasons.  Will not be available tomorrow.  On hold.

**Pull request merged**
