### PR TITLE
DATACASS-555 - use SimplePreparedStatementCreator instead of inner class

### PR DESCRIPTION
**Pull request by CodeSmell**
Allow for caching the prepared statements in the CqlTemplate if a PreparedStatementCache implementation is provided
https://jira.spring.io/browse/DATACASS-555

- [X] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [X] There is a ticket in the bug tracker for the project in our [JIRA](https://jira.spring.io/browse/DATACASS).
- [X] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [X] You submit test cases (unit or integration tests) that back your changes.
- [X] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@CodeSmell Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-cassandra&pullRequestId=129)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-data-cassandra&pullRequestId=129) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by mp911de** [comment]
Thanks for your pull request but this change isn't going to happen (see our discussion in [DATACASS-555](https://jira.spring.io/browse/DATACASS-555?focusedCommentId=159632&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-159632)). However, this pull request addresses another issue that `SimplePreparedStatementCreator` is created in two places:

* `CqlTemplate.execute(…)`
* `CqlTemplate.newPreparedStatementCreator(…)`

I'd like to keep the change to pull this into a single place (i.e. calling `newPreparedStatementCreator(…)` in `execute(…)`) so it's easier to adjust the `PreparedStatementCreator`. We have a similar issue in `ReactiveCqlTemplate`.

Care to adjust your pull request?

**Comment by CodeSmell** [comment]
Sure. Should be able to update that on Monday

**Comment by CodeSmell** [comment]
Updated the PR title to reflect the changes that are part of this PR

**Comment by mp911de** [comment]
Closing this pull request in favor of #133.

**Pull request closed without merging**
