### PR TITLE
DATACASS-56 - Cassandra paging support.

### PR DESCRIPTION
**Pull request by mp911de**
We now support forward-only paging with Cassandra through the Template API and repositories. Results in Cassandra are paged by navigating forward-only through pages described by a binary paging state encapsulated by `CassandraPageRequest` and accessible via the returned Slice. Spring Data Page's do not fit to Cassandra's paging concept because Cassandra paging is not based on limit/offset.

Page requests are applicable to a Query and as a parameter of query methods.

```java
Query query = Query.empty().pageRequest(CassandraPageRequest.first(10));
Slice<User> slice = template.slice(query, User.class);

do {

// consume slice

if (slice.hasNext()) {
slice = template.select(query, slice.nextPageable(), User.class);
} else {
break;
}
} while (!slice.getContent().isEmpty());

assertThat(ids).hasSize(100);
assertThat(iterations).isEqualTo(10);

interface UserRepository implements Repository<User, String> {

Slice<User> findAllByName(String name, Pageable pageRequest);
}
```

---

Related ticket: [DATACASS-56](https://jira.spring.io/browse/DATACASS-56).

### CODE REVIEW

**Comment by jxblum** [comment]
Reviewed, polished and merged to `master` for _Spring Data_ Kay GA.

**Comment by mp911de** [comment]
Stores can return empty results but it's possible that the paging is not finished yet. 

In general, please file a ticket or ask questions on StackOverflow as closed pull requests are not a good place for discussions.

**Comment by mustafin** [comment]
How to make it work with reactive repo? Not working with `Flux<T>`, return all results.
`Mono<Slice<T>>` yields `IncorrectResultSizeDataAccessException`

**Comment by mp911de** [comment]
Please upgrade to at least 2.1RC1, see [DATACASS-529](https://jira.spring.io/browse/DATACASS-529).

**Comment by mgezkaya** [comment]
Hi all I have written a code block to use pagination with user action here is my code I hope it helps you well.
https://gist.github.com/mgezkaya/f90e19e8e86e35cabcf22bd97325cf3a

**Pull request closed without merging**
