### PR TITLE
DATACASS-694 - Fix LocalTime conversion

### PR DESCRIPTION
**Pull request by hurelhuyag**
java.time.LocalTime to Cassandra time datatype mapping fix

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@hurelhuyag Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-cassandra&pullRequestId=166)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-data-cassandra&pullRequestId=166) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@hurelhuyag Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-cassandra&pullRequestId=166)!

**Comment by mp911de** [comment]
Care to add an integration test to `org.springframework.data.cassandra.core.convert.CassandraTypeMappingIntegrationTests` that asserts the Cassandra-specific representation of  `time`?

**Comment by hurelhuyag** [comment]
Read and Write test will work fine. Not needed to add more. Only way to check that is use cqlsh

**Comment by mp911de** [comment]
We have existing tests that prove that read and write of `LocalTime` works as expected. Applying a change to the conversion logic does not break existing tests and this is something to worry about. The reason tests didn't break is because conversion follows the same contract and our tests verify values after conversion.

Previously, the representation in Cassandra (`Row`) didn't meet how Cassandra represents `time`, therefore it is indeed necessary to add further tests to verify the Cassandra representation as seen through the driver.

**Comment by hurelhuyag** [comment]
On the other hand datastax documented time datatype is nanoseconds not milliseconds.

> Value is encoded as a 64-bit signed integer representing the number of nanoseconds since midnight. Values can be represented as strings, such as 13:30:54.234.

https://docs.datastax.com/en/archived/cql/3.3/cql/cql_reference/cql_data_types_c.html#cql_data_types_c__cqlDataTypes

**Comment by hurelhuyag** [comment]
And Cassandra `Row.getTime()` method returns long in nanoseconds

> long getTime(int i)
Returns the ith value as a long in nanoseconds since midnight.
This method uses the CodecRegistry to find a codec to convert the underlying CQL type to a Java long (for CQL type time, this will be the built-in codec).

**Comment by hurelhuyag** [comment]
And I'm not sure this kind of test is needed or not

```
@Test
	public void shouldTest(){
		assumeTrue(cassandraVersion.isGreaterThanOrEqualTo(VERSION_3_10));
		AllPossibleTypes entity = new AllPossibleTypes("1");

		entity.setLocalTime(java.time.LocalTime.of(1, 2, 3));

		operations.insert(entity);

		ResultSet resultSet = session.execute("SELECT localTime FROM AllPossibleTypes WHERE id = '1'");
		Iterator<Row> rowIt = resultSet.iterator();
		while (rowIt.hasNext()){
			Row row = rowIt.next();
			long timeNanos = row.getTime(0);
			assertThat(timeNanos).isEqualTo(3723000000000L);
		}
	}
```

**Comment by mp911de** [comment]
@hurelhuyag it is needed to prevent that this type of bug comes again.

**Comment by hurelhuyag** [comment]
2 integration test added

**Comment by mp911de** [comment]
Thanks a lot for your contribution. That's squashed, merged, polished, and backported now.

**Pull request closed without merging**
