### PR TITLE
Enable CassandraCqlClusterFactoryBean to set QueryOptions at cluster level

### PR DESCRIPTION
**Pull request by jdavisonc**
Since CassandraCqlClusterFactoryBean has not being able to set consistency level at cluster connection, I add the possibility to set QueryOptions on bean creation.

### CODE REVIEW

**Comment by olivergierke** [comment]
Thanks for the contribution! Would you mind singing the [CLA](https://support.springsource.com/spring_committer_signup), creating a ticket in our [JIRA](https://jira.spring.io/browse/DATACASS) and adding a few test cases?

**Comment by jdavisonc** [comment]
Hi Oliver, I already create the ticket, sorry for the delay :+1: https://jira.spring.io/browse/DATACASS-204

**Comment by barnesicle** [comment]
Any idea when this will be available? This would be great to be able to use.

**Comment by mp911de** [comment]
@jdavisonc Sorry for the too long delay from our side. Would you mind rebasing the PR on the current master?

**Comment by jdavisonc** [comment]
Hi @mp911de, I completed the rebase on master. Thank you for consider this PR.

**Comment by mp911de** [comment]
Thanks, that's merged with ac32151.

**Comment by nitinpadalia** [comment]
I think It can be ported to 1.3.x as well, It would be great if it can be.

**Pull request closed without merging**
