### PR TITLE
Url to project JIRA corrected in README.md

### PR DESCRIPTION
**Pull request by TheRealHaui**
- [x ] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
Well ...
- [ ] There is a ticket in the bug tracker for the project in our [JIRA](https://jira.spring.io/browse/DATACASS).
Unfortunatelly not.
And I cannot create one.
- [ ] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
Not necessary.
- [ ] You submit test cases (unit or integration tests) that back your changes.
Not necessary.
- [ ] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).
Not possible.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@TheRealHaui Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-cassandra&pullRequestId=97)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-data-cassandra&pullRequestId=97) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@TheRealHaui Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-cassandra&pullRequestId=97)!

**Comment by TheRealHaui** [comment]
Wanted to make two different pull requests.
One for the change of the README.md and one for the additional tests.

**Comment by mp911de** [comment]
Thanks for your PR. Please move the commits to separate branches. Please create Jira tickets for your changes and elaborate inside the ticket your issue/why you think a change is necessary.

This PR will update itself once you add or remove commits on your branch.

**Comment by TheRealHaui** [comment]
I've created issues in Jira.
Furthermore I'll close this pull request here and create new ones with specific branches.

**Pull request closed without merging**
