### PR TITLE
Support for reactive batch ops 

### PR DESCRIPTION
**Pull request by OlegDokuka**
https://jira.spring.io/browse/DATACASS-574

### CODE REVIEW

**Comment by OlegDokuka** [comment]
@mp911de ready to review. 

Do we really need support for inserting `Publisher`? From my perspective, we will be able to execute elements draining only on the `.execute` method invocation. In turn, it will not give any benefits since we will have to collect data before writing, so in any case, it will be kind of "waiting point" + there is danger point that one sent infinitive stream, etc

**Comment by mp911de** [comment]
Thanks for raising this item. Accepting `Publisher` is an optimization which brings a challenge of batching and awaiting. In MongoDB, we switched to accept `Mono<List<T>>` to allow deferred inserts. Using the API would require to collect items upfront (`.buffer()` or `.collectList()`) and pass in the collected objects for a batch.

For the start, we're good without accepting `Publisher`.

**Comment by OlegDokuka** [comment]
I will add support for Publisher. Let me check Mongo api first in order to be aligned.

**Comment by OlegDokuka** [comment]
@mp911de done

**Comment by mp911de** [comment]
Thanks a lot. We're heading right now towards 2.1 **RC1** so this pull request is a candidate for the second release candidate, 2.1 **RC2**.

**Comment by OlegDokuka** [comment]
@mp911de Great! Do I need to add/change something there or it is good to good but will be merged later?

**Comment by mp911de** [comment]
I haven't reviewed the pull request yet as we're currently busy with preparing 2.1 RC1.

**Comment by mp911de** [comment]
Thanks for your contribution. I had to convert spaces to tabs (please apply [our formatting settings next time](https://github.com/spring-projects/spring-data-build/blob/master/etc/ide/eclipse-formatting.xml)) and applied a round of polishing. You might be interested in https://github.com/spring-projects/spring-data-cassandra/commit/8055890ac5326881d21dd0bab444e84c54713479.

That's merged and polished now.

**Comment by OlegDokuka** [comment]
hey @mp911de. Thank you for polishing. Should I add something else there

**Comment by mp911de** [comment]
Nothing left to do here.

**Pull request closed without merging**
