### PR TITLE
Bugfix - CassandraAdminTemplate.createTable(), tableName was ignored

### PR DESCRIPTION
**Pull request by vagifzeynalov**
Please check out this little fix.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@vagifzeynalov Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-cassandra&pullRequestId=162)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-data-cassandra&pullRequestId=162) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@vagifzeynalov Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-cassandra&pullRequestId=162)!

**Comment by vagifzeynalov** [comment]
Also, as a feature request - it will be nice if you will return the execution result (boolean) for all methods of this class.
Otherwise it is impossible to guess if it was applied or not... the only option is believe! :)

**Comment by vagifzeynalov** [comment]
@jxblum @mp911de please have a look

**Comment by mp911de** [comment]
Care to elaborate on what the actual problem is? The change will change the table name on `PersistentEntity` level and so affect all subsequent operations that are not related to the table creation.

If you need to specify a table name, then this needs to happen in `CreateTableSpecification`.

**Comment by vagifzeynalov** [comment]
Hi Mark,
Thank you for the response.

>Care to elaborate on what the actual problem is? 

The problem that it is impossible to create a table with a custom name. The method signature has a `tableName` parameter but it was never used inside.

>If you need to specify a table name, then this needs to happen in CreateTableSpecification.

OK, then the table name parameter should be passed into `public CreateTableSpecification getCreateTableSpecificationFor(CassandraPersistentEntity<?> entity)` and used for `CreateTableSpecification specification = createTable(entity.getTableName());` instead of the entity name.

Feel free to close this PR if my implementation doesn't look good to you. By this PR I just wanted to bring your attention to the bug - it is impossible to create a table with a custom name.

**Comment by mp911de** [comment]
We use [Jira](https://jira.spring.io) for bug reports. I filed [DATACASS-678](https://jira.spring.io/browse/DATACASS-678) to track the bug.

> Feel free to close this PR if my implementation doesn't look good to you

I'm happy to guide you through the change now that you started looking into the code. Looking at the code, it would make the most sense to extend {{CassandraMappingContext}} by adding an overload for {{getCreateTableSpecificationFor}}.

**Comment by vagifzeynalov** [comment]
Hi Mark,
Thank you for creating the ticket, so now I can close this PR!
I agree your solution will solve this issue as well.
`public CreateTableSpecification getCreateTableSpecificationFor(CqlIdentifier tableName, CassandraPersistentEntity<?> entity)`

**Comment by mp911de** [comment]
Do you want to submit a PR for the fix we agreed on or do you want us to fix the issue?

**Comment by vagifzeynalov** [comment]
@mp911de I can submit a PR, it looks pretty straight forward and simple.

**Pull request closed without merging**
